---
title: "Notes 9-20"
author: "Ryan Thomas"
date: "September 18, 2015"
output: html_document
---

```{r}
setwd("~/Documents/r/directories/data/intro_data")

isit <- read.table("ISIT.txt", header = TRUE, sep = "\t")
str(isit)
table(isit$Station)
```

Let's pull out just the data for station 1.
```{r}
head(isit[isit$Station == 1, ])

#How many records in Station 1?
nrow(isit[isit$Station == 1, ])
```

Now we can take the descriptive stats for each station.
```{r}
sum1 <- summary(isit$SampleDepth[isit$Station == 1])
sum2 <- summary(isit$SampleDepth[isit$Station == 2])
sum3 <- summary(isit$SampleDepth[isit$Station == 3])
# and so on.

sum1
```

4. What are the minimum, median, mean, max sampled depth at Station 1 and Station 3?
```{r}
isit_st1 <- isit[isit$Station == 1,]
str(isit_st1)
summary(isit_st1$SampleDepth)

summary(isit[isit$Station == 1,])
summary(isit[isit$Station == 3,])

```

To find the stations that have below average number of observations:
```{r}
StationFreq <- data.frame(table(isit$Station))
StationFreq$Var1[StationFreq$Freq >= mean(table(isit$Station))]

hiStation <- as.vector(StationFreq$Var1[StationFreq$Freq >= mean(table(isit$Station))])

hiStation
```

```{r}
isit_hiStation <- isit[isit$Station == 2 | isit$Station == 9 | isit$Station == 10 | isit$Station == 13 | isit$Station == 14 | isit$Station == 15 | isit$Station == 17 | isit$Station == 18 | isit$Station == 19 , ]

unique(isit_hiStation$Station)
```


```{r}
isit2002 <- isit[isit$Year == 2002, ]
head(isit2002)
```

```{r}
isitApril <- isit[isit$Month == 4, ]
head(isitApril)
```

```{r}
isitDepth2000 <- isit[isit$SampleDepth > 2000, ]
head(isitDepth2000)
```

```{r}
asc <- isit[order(isit$SampleDepth, decreasing = FALSE),]
head(asc)
```

```{r}
April2000 <- isit[isit$SampleDepth > 2000 & isit$Month == 4, ]
head(April2000)
```

```{r}
write.table(April2000, file = "April2000.txt")
```

```{r}
isit$Year <- factor(isit$Year)
isit$Month <- factor(isit$Month)
```
