---
title: "Notes 9-28"
author: "Ryan Thomas"
date: "September 28, 2015"
output: html_document
---

```{r}
setwd("~/Documents/r/directories/data/intro_data")

deer <- read.table("deer.txt", header = TRUE, sep = "\t")
str(deer)
```

```{r}
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), lwd = 2)

# top left
plot(Ecervi ~ LCT, data = deer, main = "default scatterplot")

# top right
plot(Ecervi ~ LCT, data = deer, 
     main = "Modified axes", 
     pch = 16, 
     tcl = 0.3, 
     las = 1, 
     # mpg = c(fill this in later - what are these numbers doing?)
     mgp = c(2.5, 0.5, 0))
```

```{r}
# The bottom left is built first as an empty shell of a graphic and then the 
# data are added after.
plot(Ecervi ~ LCT, data = deer, 
     main = "Modified axes", 
     pch = 16, 
     tcl = 0.3, 
     las = 1, 
     mgp = c(2.5, 0.5, 0), 
     type = "n")
  points(Ecervi ~ LCT, col = "grey10", 
       pch = 20, 
       data = deer[deer$Sex == 1, ], 
       cex = .5)
  points(Ecervi ~ LCT, 
       col = "grey70", 
       pch = 17, 
       data = deer[deer$Sex == 2, ], 
       cex = .5)
  legend("topleft", pch = c(20, 17), col = c("grey10",  "grey70"), legend = c("male", "female"))


plot(Ecervi ~ LCT, data = deer, 
     main = "Modified axes", 
     pch = 16, 
     tcl = 0.3, 
     las = 1, 
     mgp = c(2.5, 0.5, 0), 
     type = "n")
  points(Ecervi ~ LCT, col = "grey10", 
       pch = 20, 
       data = deer[deer$Sex == 1, ], 
       cex = 2 * 1/clas1_4)
  points(Ecervi ~ LCT, 
       col = "grey70", 
       pch = 17, 
       data = deer[deer$Sex == 2, ], 
       cex = 2 * 1/clas1_4)
    legend("topleft", 
           pch = c(20, 17), 
           col = c("grey10",  "grey70"), 
           legend = c("male", "female")
           )

```

Now we'll make a nice histogram.
```{r}
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), lwd = 2)

```

Excercises:
1. Histogram
```{r}
par(mfrow = c(2,2), mar = c(3,3,2,1), lwd = 2)
hist(deer$LCT, main = "default histogram")
hist(deer$LCT, breaks = 5, main = "breaks = 5")
hist(deer$LCT, breaks = seq(from = 0, to = 250, by = 5), main = "breaks = seq()")
hist(deer$LCT, breaks = seq(from = 0, to = 250, by = 5), freq = FALSE, main = "probability density")
```

Dreaded Pie
```{r}
# Knitr note: have to reset the wd for every code chunk
setwd("~/Documents/r/directories/data/intro_data")

bfcases <- read.table(file = "BirdFluCases.txt", header = TRUE)
names(bfcases)
str(bfcases)

# make a data frame with the data we want to graph
cases <- rowSums(bfcases[, 2:16])
names(cases) <- bfcases[, 1]
cases

# set up grid and margins
par(mfrow = c(2,2), mar = c(3, 3, 2, 1))

# make pie charts
pie(cases, main = "Ordinary pie chart")
pie(cases, col = gray(seq(0.4, 0.1, length = 6)), clockwise = TRUE, main = "Grey colors")
pie(cases, col = rainbow(6), clockwise = TRUE, main = "Rainbow colors")

# If plotrix is not installed, install it. Use `install.packages("plotrix")`.
if(!require("plotrix"))
  stop("you need to install plotrix")

# make a 3d chart... dunno why?
pie3D(cases, labels = names(cases), explode = 0.1, main = "3D pie chart", labelcex = 0.6)

```

```{r}
# tapply applies the FUNCTION to the data for every INDEX
deer.mean <- tapply(deer$LCT, 
                    INDEX = deer$Sex, 
                    FUN = mean, 
                    na.rm = TRUE)
deer.sd <- tapply(deer$LCT, INDEX = deer$Sex, FUN = sd, na.rm = TRUE)

deer.mean
deer.sd
```

```{r}
par(mfrow = c(2,2), mar = c(3, 3, 2, 1))
barplot(deer.mean, 
        xlab = "Sex", 
        ylab = "Length (cm)", 
        ylim = c(0, 200), 
        col = c('grey10', 'grey70'))
xvals <- barplot(deer.mean, plot = FALSE)
xvals
arrows(x0 = xvals, y0 = deer.mean, 
       x1 = xvals, 
       y1 = deer.mean + deer.sd, 
       lwd = 2, 
       angle = 90, 
       length = 0.1)
```


```{r}
setwd("~/Documents/r/directories/data/intro_data")
Benthic <- read.table("RIKZ2.txt", header = TRUE, sep = '\t')
plot(y = Benthic$Richness, x = Benthic$NAP,
  xlab = "Mean high tide", ylab = "Species richness",
  xlim = c(-1.75,2), ylim = c(0,20),
  type = "p", axes = FALSE
)

axis(side = 2, at = Benthic$Richness, tcl = 1)
axis(side = 1, at = c(-1.75, 0, 2), labels = c("Sea", "Water line", "Dunes"))

# run a linear regression model: lm()
M0 <- lm(Richness ~ NAP, data = Benthic)
# plot the fitted line
abline(M0)
```

```{r}
plot(y = Benthic$Richness, x = Benthic$NAP,
  xlab = "Mean high tide", ylab = "Species richness",
  xlim = c(-1.75,2), ylim = c(0,20),
  type = "p", axes = FALSE
)

axis(side = 2, at = Benthic$Richness, tcl = 1)
axis(side = 1, at = c(-1.75, 0, 2), labels = c("Sea", "Water line", "Dunes"))

# run a linear regression model: lm()
M0 <- lm(Richness ~ NAP, data = Benthic)
# plot the fitted line
abline(M0)
```

```{r}
plot(y = Benthic$Richness, x = Benthic$NAP,
xlab = "Mean high tide",
xlim = c(-1.75,2), ylim = c(0,20),
type = "p", axes = TRUE, ylab = expression(paste(delta^{15}, "N")
))
```